# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex Momchilov
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://momchilov.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  amomchilov
linkedin_username: amomchilov

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-favicon-generator

header_pages:
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

favicon-generator:
  source: assets/favicons/favicon.svg # by default automatically find favicon.* image in source root
  destination: assets/favicons # where generated favicons are stored
  color: '#000000' # Foreground color; used in site.webmanifest
  background: '#ffffff' # Background color; used in site.webmanifest
  icons:
  - file: favicon.ico # File name for the icon
    size: '16,24,32,48' # Sizes to generate; only .ico files can have multiple sizes
    ref: nil # Always placed in the site root regardless of the destination option
  - file: favicon-16.png
    size: 16
    ref: link/icon # Referenced from a <link rel="icon"> tag
  - file: favicon-32.png
    size: 32 # Icons are always square, so only one dimension is necessary
    ref: link/icon
  - file: favicon.svg
    size: nil # Size is ignored for SVG favicons
    ref: link/icon
  - file: apple-touch-icon.png
    size: 180
    ref: link/apple-touch-icon # Referenced from a <link rel="apple-touch-icon"> tag
  - file: android-chrome-192.png
    size: 192
    ref: manifest # Referenced from a generated site.webmanifest file
                  # The webmanifest is automatically linked using a <link rel="manifest"> tag
  - file: android-chrome-512.png
    size: 512
    ref: manifest
