# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Use 'bundle exec jekyll serve --livereload` for live-reloading pages on changes.

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

minimal_mistakes_skin: "default"
# Automatically switch between the light and dark skins. Based on:
# https://humberto.stein-shiromoto.net/posts/2022/09/27/blog-post_adding_theme_switch_to_minimal_mistakes
minimal_mistakes_dark_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  # - jekyll-favicon-generator

locale: "en-CA"
title: &name "Alex Momchilov"
title_separator: "|"
subtitle: ~
description: &description >-
  Hey I'm Alex, a software engineer based in Toronto.
url: "https://momchilov.ca"
baseurl: "" # the subpath of your site, e.g. /blog
repository: "amomchilov/amomchilov.github.io"

defaults: # Default "front matter" for each page. https://jekyllrb.com/docs/configuration/front-matter-defaults/
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      author_profile: true
      share: true

author: # Sidebar data
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/avatar/headshot-original-110x110@2x.jpeg"
  bio              : "Staff Engineer @ Shopify"
  location         : "Toronto 🇨🇦"
  links: # icons come from https://fontawesome.com/icons
    - icon: "fa-solid fa-location-dot"
      label: Toronto, Canada

    - icon: "fa-brands fa-github"
      label: "GitHub"
      url: https://github.com/AMomchilov

    - icon: "fa-brands fa-linkedin"
      label: LinkedIn
      url: https://www.LinkedIn.com/in/AMomchilov

    - icon: "fa-brands fa-stack-overflow"
      label: StackOverflow
      url: https://StackOverflow.com/users/3141234/Alexander

favicon-generator:
  source: assets/favicons/favicon.svg # by default automatically find favicon.* image in source root
  destination: assets/favicons # where generated favicons are stored
  color: '#000000' # Foreground color; used in site.webmanifest
  background: '#ffffff' # Background color; used in site.webmanifest
  icons:
  - file: favicon.ico # File name for the icon
    size: '16,24,32,48' # Sizes to generate; only .ico files can have multiple sizes
    ref: nil # Always placed in the site root regardless of the destination option
  - file: favicon-16.png
    size: 16
    ref: link/icon # Referenced from a <link rel="icon"> tag
  - file: favicon-32.png
    size: 32 # Icons are always square, so only one dimension is necessary
    ref: link/icon
  - file: favicon.svg
    size: nil # Size is ignored for SVG favicons
    ref: link/icon
  - file: apple-touch-icon.png
    size: 180
    ref: link/apple-touch-icon # Referenced from a <link rel="apple-touch-icon"> tag
  - file: android-chrome-192.png
    size: 192
    ref: manifest # Referenced from a generated site.webmanifest file
                  # The webmanifest is automatically linked using a <link rel="manifest"> tag
  - file: android-chrome-512.png
    size: 512
    ref: manifest

exclude:
  - "online-cv/"
  - "*.sync-conflict*"

sass:
  sass_dir: _sass
  style: compressed

host: 0.0.0.0 # Host to entire LAN, not just localhost.
